# Generated by Django 5.2.16 on 2026-07-22 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Texto')),
                ('priority', models.IntegerField(choices=[(11, 'Baixíssima'), (22, 'Baixa'), (33, 'Média'), (44, 'Alta'), (55, 'Altíssima')], default=33, verbose_name='Prioridade')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de vencimento')),
                ('number', models.PositiveIntegerField(db_index=True, editable=False, unique=True, verbose_name='Número')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('shared_users', models.ManyToManyField(blank=True, related_name='shared_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
