# Generated by Django 5.2.16 on 2026-07-22 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_board_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['board', 'position'], 'verbose_name': 'Coluna', 'verbose_name_plural': 'Colunas'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-priority', 'due_date', 'created_at'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.column', verbose_name='Coluna'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Posição na coluna'),
        ),
    ]
