# Generated by Django 5.2.16 on 2026-07-22 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketboardtransition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketBoardTransition',
            new_name='TicketColumnTransition',
        ),
    ]
